Items = { -- will mods want to append to this?
	-- format: tag, image, r, g, b
	{ "alchemist_key", "mods/boss_reworks/files/spells/forgotten/key.png", 0, 119, 63 },
	{ "wand", "mods/boss_reworks/files/spells/forgotten/wand.png", 0, 66, 115 },
	{ "potion", "mods/boss_reworks/files/spells/forgotten/potion.png", 136, 136, 136 },
	{ "br_pouch", "mods/boss_reworks/files/spells/forgotten/pouch.png", 81, 61, 17 },
	{ "seed_a", "mods/boss_reworks/files/spells/forgotten/seed_a.png", 79, 79, 79 },
	{ "seed_b", "mods/boss_reworks/files/spells/forgotten/seed_b.png", 55, 0, 0 },
	{ "seed_c", "mods/boss_reworks/files/spells/forgotten/seed_c.png", 198, 181, 65 },
	{ "seed_d", "mods/boss_reworks/files/spells/forgotten/seed_d.png", 146, 126, 26 },
	{ "seed_e", "mods/boss_reworks/files/spells/forgotten/seed_e.png", 255, 255, 255 },
	{ "seed_f", "mods/boss_reworks/files/spells/forgotten/seed_f.png", 0, 0, 0 },
	{ "br_orb", "mods/boss_reworks/files/spells/forgotten/orb.png", 25, 111, 146 },
	{ "normal_tablet", "mods/boss_reworks/files/spells/forgotten/tablet.png", 41, 148, 84 },
	{ "forged_tablet", "mods/boss_reworks/files/spells/forgotten/tablet_forged.png", 84, 78, 45 },
	-- {"br_hamis",      "mods/boss_reworks/files/spells/forgotten/hamis.png",         28, 11, 43},
	{ "this_is_sampo", "mods/boss_reworks/files/spells/forgotten/sampo.png", 56, 138, 174 },
	{ "evil_eye", "mods/boss_reworks/files/spells/forgotten/evil_eye.png", 146, 80, 93 },
	{ "br_musicstone", "mods/boss_reworks/files/spells/forgotten/musicstone.png", 45, 160, 122 },
	{ "card_summon_portal_broken", "mods/boss_reworks/files/spells/forgotten/broken_spell.png", 84, 12, 87 },
	{ "statue_hand", "mods/boss_reworks/files/spells/forgotten/monk_hand.png", 46, 46, 46 },
	{ "br_moon", "mods/boss_reworks/files/spells/forgotten/moon.png", 130, 123, 120 },
	{ "broken_wand", "mods/boss_reworks/files/spells/forgotten/broken_wand.png", 177, 39, 168 },
	{ "br_wandcore", "mods/boss_reworks/files/spells/forgotten/wandcore.png", 21, 156, 75 },
	{ "musicmachine", "mods/boss_reworks/files/spells/forgotten/musicmachine.png", 174, 171, 105 },
}
