    -- included some unused/nonexistent spells in here in case mods add spells with that id

-- this also includes modded spells
return {
    {"LIGHT_BULLET", "LIGHT_BULLET_TRIGGER", "LIGHT_BULLET_TRIGGER_2", "LIGHT_BULLET_TIMER", "GRAHAM_SPARK_BOLT", "COPITH_LIGHT_BULLET_DEATH_TRIGGER", "LIGHT_BULLET_AUTO"--[[More Stuff]], "KUPOLI_LIGHT_BULLET_TIER_2",},
    {"BULLET", "BULLET_TRIGGER", "BULLET_TIMER", "KUPOLI_SOUL_ARROW",},
    {"HEAVY_BULLET", "HEAVY_BULLET_TRIGGER", "HEAVY_BULLET_TIMER",},
    {"SLOW_BULLET", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TIMER", "COPITH_SLOW_BULLET_TIMER_2", "COPITH_SLOW_BULLET_TIMER_N",},
    {"BLACK_HOLE", "BLACK_HOLE_DEATH_TRIGGER", "BLACK_HOLE_BIG", "BLACK_HOLE_GIGA",},
    {"WHITE_HOLE", "WHITE_HOLE_BIG", "WHITE_HOLE_GIGA",},
    {"TENTACLE_PORTAL", "TENTACLE", "TENTACLE_TIMER", "BLOODTENTACLE",},
    {"DECOY", "DECOY_TRIGGER", "DECOY_TIMER",},
    {"SPITTER", "SPITTER_TRIGGER", "SPITTER_TIMER", "SPITTER_TIER_2", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_3", "SPITTER_TIER_3_TIMER",},
    {"BUBBLESHOT", "BUBBLESHOT_TRIGGER", "GRAHAM_BUBBLES",},
    {"SPELLBOUND_CALTROPS", "DISC_BULLET", "DISC_BULLET_BIG", "DISC_BULLET_BIGGER", "DISC_BULLET_STILL"--[[More Stuff]], "COPITH_ZENITH_DISC",},
    {"BOUNCY_ORB", "BOUNCY_ORB_TIMER",},
    {"LANCE", "LANCE_HOLY",},
    {"ROCKET", "ROCKET_TIER_2", "ROCKET_TIER_3", "KUPOLI_SOUL_BLAST",},
    {"GRENADE", "GRENADE_TRIGGER", "GRENADE_TIER_2", "GRENADE_TIER_3", "GRENADE_ANTI", "GRENADE_LARGE", "KUPOLI_SOUL_BALL",},
    {"MINE", "MINE_DEATH_TRIGGER",},
    {"PIPE_BOMB", "PIPE_BOMB_DEATH_TRIGGER",},
    {"LASER", "MEGALASER",},
    {"LASER_EMITTER", "LASER_EMITTER_FOUR", "LASER_EMITTER_CUTTER", "COPITH_LASER_EMITTER_SMALL", "KUPOLI_BACKWARDS_PLASMA", "SOLAR_RAY"--[[More Stuff]],},
    {"DIGGER", "POWERDIGGER", "CHAINSAW",},
    {"LUMINOUS_DRILL", "LASER_LUMINOUS_DRILL", "COPITH_LUMINOUS_BLADE",},
    {"KUPOLI_HEALING_ARROW", "HEAL_BULLET", "ANTIHEAL",}, -- how strong?
    {"SPIRAL_SHOT", "MAGIC_SHIELD", "BIG_MAGIC_SHIELD", "KUPOLI_SOUL_GUARD",},
    {"FIREBALL", "ICEBALL",},
    {"FREEZING_GAZE", "GRAHAM_INFERNAL_GLARE",},
    {"BOMB_HOLY", "BOMB_HOLY_GIGA",},
    {"SUMMON_EGG", "SUMMON_HOLLOW_EGG", "COPITH_SUMMON_HAMIS",},
    {"TNTBOX", "TNTBOX_BIG",},
    {"SWARM_FLY", "SWARM_FIREBUG", "SWARM_WASP", "FRIEND_FLY",},
    {"DEATH_CROSS", "DEATH_CROSS_BIG", "APOTHEOSIS_DEATH_CROSS_OMEGA",}, -- does this defeat the purpose of doing the labrinth quest? (if it's not unlocked yet, then it won't spawn)
    {"WALL_HORIZONTAL", "WALL_VERTICAL", "WALL_SQUARE",},
    {"TEMPORARY_WALL", "TEMPORARY_PLATFORM", "COPITH_TEMPORARY_CIRCLE",},
    {"LONG_DISTANCE_CAST", "TELEPORT_CAST", "SUPER_TELEPORT_CAST", "CASTER_CAST", "COPITH_PROJECTILE_CAST",}, -- how strong?
    {"MIST_RADIOACTIVE", "MIST_ALCOHOL", "MIST_SLIME", "MIST_BLOOD", "GRAHAM_MIST_SWEET", "APOTHEOSIS_MIST_ATTUNIUM",},
    {"CIRCLE_FIRE", "CIRCLE_ACID", "CIRCLE_OIL", "CIRCLE_WATER", "GRAHAM_CIRCLE_SWEET", "GRAHAM_CIRCLE_ANGY", "COPITH_CIRCLE_RANDOM",},
    {"MATERIAL_WATER", "MATERIAL_OIL", "MATERIAL_BLOOD", "MATERIAL_ACID", "MATERIAL_CEMENT", "GRAHAM_MATERIAL_PURE", "GRAHAM_MATERIAL_RADIOACTIVE", "COPITH_MATERIAL_LAVA", "COPITH_MATERIAL_MAGIC_LIQUID_POLYMORPH", "COPITH_MATERIAL_RANDOM", "APOTHEOSIS_MATERIAL_ALCOHOL", "APOTHEOSIS_MATERIAL_SLIME", "MATERIAL_METAL"--[[More Stuff]],},
    {"TELEPORT_PROJECTILE", "APOTHEOSIS_ALT_FIRE_TELEPORT", "TELEPORT_PROJECTILE_SHORT", "APOTHEOSIS_ALT_FIRE_TELEPORT_SHORT", "TELEPORT_PROJECTILE_STATIC", "KUPOLI_TRIGGER_RETURN", "TELEPORT_PROJECTILE_CLOSER", "SWAPPER_PROJECTILE", "APOTHEOSIS_ALT_FIRE_SWAPPER", "BR_LONGTELETRIGGER", "BR_SHORTTELETRIGGER", "GRAHAM_TELEPORT", "COPITH_ELECTRIC_TELEPORT", "COPITH_TRANSMISSION_CAST", "KUPOLI_SOUL_DASH",}, -- should transmission cast be included in this list?
    {"NUKE", "NUKE_GIGA",},
    {"TOUCH_GOLD", "TOUCH_WATER", "TOUCH_OIL", "TOUCH_ALCOHOL", "TOUCH_BLOOD", "TOUCH_SMOKE", "TOUCH_PISS", "TOUCH_GRASS", "GRAHAM_TOUCH_ICE", "COPITH_TOUCH_RANDOM",},
    {"DESTRUCTION", "MASS_POLYMORPH", "CESSATION", "COPITH_POLYMORPH", "COPITH_DIE",},
    {"BURST_2", "BURST_3", "BURST_4", "BURST_8", "BURST_X", "APOTHEOSIS_RANDOM_BURST",},
    {"SCATTER_2", "SCATTER_3", "SCATTER_4", "COPITH_SCATTER_6", "COPITH_SCATTER_8",},
    {"I_SHAPE", "Y_SHAPE", "T_SHAPE", "W_SHAPE", "PENTAGRAM_SHAPE", "CIRCLE_SHAPE", "COPITH_NGON_SHAPE", "APOTHEOSIS_SHAPE_WALL",},
    {"I_SHOT", "Y_SHOT", "T_SHOT", "W_SHOT", "QUAD_SHOT", "PENTA_SHOT", "HEXA_SHOT", "APOTHEOSIS_SHOT_WALL",},
    {"SPREAD_REDUCE", "HEAVY_SPREAD", "COPITH_SPREAD",},
    {"LIFETIME", "LIFETIME_DOWN", "LIFETIME_INFINITE", "COPITH_LIFETIME_RANDOM",},
    {"SLOW_BUT_STEADY", "RECHARGE", "COPITH_RECHARGE_UNSTABLE", "COPITH_RECHARGE_ENGINE", "KUPOLI_SOUL_RECHARGE",},
    {"EXPLOSION_REMOVE", "EXPLOSION_TINY", "EXPLOSIVE_PROJECTILE",},
    {"MANA_REDUCE", "BLOOD_MAGIC", "COPITH_AVERAGE_MANA", "COPITH_MANA_DELTA", "COPITH_MANA_RANDOM", "COPITH_MANA_EFFICIENCY", "COPITH_MANA_ENGINE", "KUPOLI_SOUL_IS_MANA", "COPITH_PASSIVE_MANA", "GRAHAM_PASSIVES",}, -- how strong? (adding these modded spells might make this even stronger--or it could add a TON of convenience and flavor to wand builds)
    {"MONEY_MAGIC", "BLOOD_TO_POWER", "DAMAGE_FOREVER", "SPELLS_TO_POWER", "ESSENCE_TO_POWER", "COPITH_ARCANA_TO_POWER" , "COPITH_SLOTS_TO_POWER", "APOTHEOSIS_KINDNESS_TO_POWER", "KUPOLI_SOULS_TO_POWER",},
    {"GRAVITY", "COPITH_LEVITY_SHOT", "GOKI_ZERO_GRAVITY", "GRAVITY_ANTI",}, -- how strong?
    {"SINEWAVE", "CHAOTIC_ARC", "PINGPONG_PATH", "AVOIDING_ARC", "FLOATING_ARC", "ORBIT_SHOT", "PHASING_ARC", "SPIRALING_SHOT", "TRUE_ORBIT", "COPITH_STICKY_SHOT", "COPITH_ZIPPING_ARC", "WALL_BOLT"--[[More Stuff]],},
    {"HORIZONTAL_ARC", "LINE_ARC", "VERTICAL_ARC", "COPITH_VERTICAL_ARC",},
    {"BOUNCE", "REMOVE_BOUNCE", "BOUNCE_EXPLOSION", "BOUNCE_SPARK", "BOUNCE_LASER", "BOUNCE_LASER_EMITTER", "BOUNCE_LARPA", "BOUNCE_SMALL_EXPLOSION", "BOUNCE_LIGHTNING", "BOUNCE_HOLE", "COPITH_DAMAGE_BOUNCE", "COPITH_HYPER_BOUNCE", "SPELLBOUND_RUBBER_COATING", "COPITH_HOMING_BOUNCE", "COPITH_HOMING_BOUNCE_CURSOR",},
    {"HOMING", "ANTI_HOMING", "HOMING_WAND", "HOMING_SHORT", "HOMING_ROTATE", "HOMING_SHOOTER", "AUTOAIM", "HOMING_ACCELERATING", "HOMING_CURSOR", "COPITH_PSYCHIC_SHOT", "COPITH_HOMING_ANTI_SHOOTER", "COPITH_HOMING_INTERVAL", "COPITH_HOMING_MACROSS", "APOTHEOSIS_HOMING_DELAYED", "COPITH_HOMING_SEEKER", "APOTHEOSIS_RANDOM_HOMING", "KUPOLI_RANDOM_HOMING", "SPELLBOUND_ACTIVE_HOMING", "GOKI_CLINGING_SHOT", "SPELLBOUND_PATHFINDING",}, -- should spellbound's control be put in here? should clinging shot be in here? also both Copi's Things and Apotheosis have a version of Delayed Homing (macross and delayed). Apoth and Kupoli also both have a version of random homing
    {"DAMAGE", "DAMAGE_RANDOM", "BLOODLUST", "ZERO_DAMAGE", "HEAVY_SHOT", "LIGHT_SHOT", "COPITH_DAMAGE_CRITICAL", "COPITH_DIMIGE", "COPITH_DAMAGE_ENGINE", "KUPOLI_SOUL_STRIKE", "SPELLBOUND_SLOW_PROJECTILES",},
    {"KNOCKBACK", "RECOIL", "RECOIL_DAMPER", "COPITH_REDUCE_KNOCKBACK",},
    {"SPEED", "ACCELERATING_SHOT", "DECELERATING_SHOT", "GRAHAM_STASIS", "COPITH_ANCHORED_SHOT", "COPITH_INVERT", "COPITH_SLOW", "KUPOLI_SOUL_SPEED",},
    {"CLUSTERMOD", "UNSTABLE_GUNPOWDER",},
    {"WATER_TO_POISON", "BLOOD_TO_ACID", "LAVA_TO_BLOOD", "TOXIC_TO_ACID", "LIQUID_TO_EXPLOSION", "STATIC_TO_SAND", "COPITH_LIQUID_TO_SOIL", "COPITH_POWDER_TO_WATER", "COPITH_POWDER_TO_STEEL", "COPITH_STATIC_TO_EXPLOSION", "KUPOLI_BLOOD_TO_STEAM", "GRAHAM_EXTINGUISHER", "GRAHAM_POWDER_EVAPORATION", "GRAHAM_ROT", "AA_POTION_TO_GAS",},
    {"EXPLOSION", "EXPLOSION_LIGHT", "FIRE_BLAST", "POISON_BLAST", "ALCOHOL_BLAST", "CC_GREASE_BLAST", "THUNDER_BLAST", "KUPOLI_SOUL_EXPLOSION",},
    {"BERSERK_FIELD", "POLYMORPH_FIELD", "CHAOS_POLYMORPH_FIELD", "ELECTROCUTION_FIELD", "FREEZE_FIELD", "TELEPORTATION_FIELD", "LEVITATION_FIELD", "SHIELD_FIELD", "COPITH_CHARM_FIELD", "COPITH_CIRCLE_ANCHOR", "COPITH_CIRCLE_BOOST", "COPITH_LARPA_FIELD", "KUPOLI_REAPING_FIELD", "GRAHAM_TRANSLOCATION", "SPELLBOUND_SUFFOCATION_FIELD",}, -- no Circle of Vigor nor Copi's Circle of Divine Blessing
    {"PROJECTILE_TRANSMUTATION_FIELD", "PROJECTILE_THUNDER_FIELD", "PROJECTILE_GRAVITY_FIELD",},
    {"VACUUM_POWDER", "VACUUM_LIQUID", "VACUUM_ENTITIES",},
    {"SEA_LAVA", "SEA_ALCOHOL", "SEA_OIL", "SEA_WATER", "SEA_SWAMP", "SEA_ACID", "SEA_ACID_GAS", "SEA_MIMIC", "COPITH_SEA_RANDOM", "APOTHEOSIS_POTION_TO_SEA", "APOTHEOSIS_SEA_BERSERK", "CC_SEA_OF_LIGHTNING", "CC_SEA_OF_METHANE",},
    {"CLOUD_WATER", "CLOUD_OIL", "CLOUD_BLOOD", "CLOUD_ACID", "CLOUD_THUNDER", "COPITH_CLOUD_DISK_BULLET", "COPITH_CLOUD_RANDOM", "APOTHEOSIS_CLOUD_VOLCANIC", "CC_CLOUD_CRYSTAL", "CC_CLOUD_GUNPOWDER", "CC_CLOUD_SPARKLING",}, -- Copi's Things's Healthy Cloud not included on purpose
    {"HITFX_BURNING_CRITICAL_HIT", "HITFX_CRITICAL_WATER", "HITFX_CRITICAL_OIL", "HITFX_CRITICAL_BLOOD", "HITFX_TOXIC_CHARM", "GRAHAM_TOXIC_CRIT", "COPITH_HITFX_CRITICAL_CHARM", "COPITH_HITFX_CRITICAL_ELECTROCUTED", "COPITH_HITFX_CRITICAL_FROZEN", "APOTHEOSIS_HITFX_CRITICAL_DRUNK",},
    {"HITFX_EXPLOSION_SLIME", "HITFX_EXPLOSION_SLIME_GIGA", "HITFX_EXPLOSION_ALCOHOL", "HITFX_EXPLOSION_ALCOHOL_GIGA", "APOTHEOSIS_HITFX_MUDMAN_SLIMY",},
    {"ROCKET_DOWNWARDS", "ROCKET_OCTAGON",},
    {"FIREBALL_RAY", "LIGHTNING_RAY", "TENTACLE_RAY", "LASER_EMITTER_RAY", "FIREBALL_RAY_LINE", "COPITH_GRAPPLING_HOOK_SHOT", "COPITH_SILVER_BULLET_RAY", "COPITH_SILVER_BULLET_RAY_6", "COPITH_SILVER_BULLET_RAY_SPIN", "APOTHEOSIS_CURSED_ORB_RAY", "APOTHEOSIS_ICEBALL_RAY", "APOTHEOSIS_NUKE_RAY", "APOTHEOSIS_SAWBLADE_RAY", "CC_RADIOACTIVE_SHOT", "SPELLBOUND_BLOOM_PROJECTILES",},
    {"FIREBALL_RAY_ENEMY", "LIGHTNING_RAY_ENEMY", "TENTACLE_RAY_ENEMY", "GRAVITY_FIELD_ENEMY", "COPITH_GRAPPLING_HOOK_RAY_ENEMY", "COPITH_SILVER_BULLET_RAY_ENEMY", "APOTHEOSIS_CURSED_ORB_RAY_ENEMY", "APOTHEOSIS_ICEBALL_RAY_ENEMY", "APOTHEOSIS_NUKE_RAY_ENEMY", "APOTHEOSIS_SAWBLADE_RAY_ENEMY", "CC_ANTIMATTER_FIELD_ENEMY",},
    {"CURSE_WITHER_PROJECTILE", "CURSE_WITHER_PROJECTILE", "CURSE_WITHER_EXPLOSION", "CURSE_WITHER_MELEE", "CURSE_WITHER_ELECTRICITY", "CURSE",},
    {"ORBIT_DISCS", "ORBIT_FIREBALLS", "ORBIT_NUKES", "ORBIT_LASERS", "ORBIT_LARPA", "GRAHAM_ORBIT_BLUE",},
    {"ARC_ELECTRIC", "ARC_FIRE", "ARC_GUNPOWDER", "ARC_POISON", "COPITH_ARC_CONCRETE", "COPITH_BARRIER_ARC",},
    {"CRUMBLING_EARTH", "CRUMBLING_EARTH_PROJECTILE",},
    {"ACID_TRAIL", "POISON_TRAIL", "OIL_TRAIL", "WATER_TRAIL", "GUNPOWDER_TRAIL", "FIRE_TRAIL", "BURN_TRAIL", "COPITH_FREEZING_VAPOUR_TRAIL", "COPITH_SOIL_TRAIL", "COPITH_VOID_TRAIL", "COPITH_WOOD_BRUSH", "AA_REPULTIUM_TRAIL", "APOTHEOSIS_TRAIL_LARGER", "GRAHAM_INTENSIFY",}, -- do trail_larger and indensify go here?
    {"TORCH", "TORCH_ELECTRIC", "FLASHLIGHT"--[[More Stuff]],},
    {"ENERGY_SHIELD", "ENERGY_SHIELD_SECTOR", "GRAHAM_UMBRELLA", "GRAHAM_UNBRELLA", "GRAHAM_SLICESHIELD", "COPITH_ENERGY_SHIELD_DIRECTIONAL", "COPITH_SHIELD_ENGINE", "COPITH_SHIELD_SAPPER",},
    {"OCARINA_A", "OCARINA_B", "OCARINA_C", "OCARINA_D", "OCARINA_E", "OCARINA_F", "OCARINA_GSHARP", "OCARINA_A2",},
    {"KANTELE_A", "KANTELE_D", "KANTELE_DIS", "KANTELE_E", "KANTELE_G",},
    {"RANDOM_SPELL", "RANDOM_PROJECTILE", "RANDOM_MODIFIER", "RANDOM_STATIC_PROJECTILE",}, -- add the rest of the random spells?
    {"DRAW_RANDOM", "DRAW_RANDOM_X3", "DRAW_3_RANDOM",},
    {"ALL_NUKES", "ALL_DISCS", "ALL_ROCKETS", "ALL_DEATHCROSSES", "ALL_BLACKHOLES", "ALL_ACID", "APOTHEOSIS_SPELLS_TO_CATS", "KUPOLI_ALL_WORMS",}, -- does spells to cats belong here?
    {"ADD_TRIGGER", "ADD_TIMER", "ADD_DEATH_TRIGGER", "COPITH_TRIGGER_DAMAGE_RECEIVED",}, -- ...this feels out of place. Will probably remove.
    {"LARPA_CHAOS", "LARPA_DOWNWARDS", "LARPA_UPWARDS", "LARPA_CHAOS_2", "LARPA_DEATH", "COPITH_HITFX_LARPA", "COPITH_LARPA_FORWARDS", "COPITH_RECURSIVE_LARPA", "APOTHEOSIS_LARPA_DELAYED",},
    {"ALPHA", "GAMMA", "COPITH_DELTA", "ZETA", "APOTHEOSIS_KAPPA", "MU", "SIGMA", "TAU", "PHI", "APOTHEOSIS_CHI", "COPITH_PSI", "OMEGA",}, -- should be actual greek alphabet order
    {"DIVIDE_2", "DIVIDE_3", "DIVIDE_4", "DIVIDE_10",},
    {"METEOR_RAIN", "WORM_RAIN",},
    {"IF_ENEMY", "IF_PROJECTILE", "IF_HP", "IF_HALF", "IF_ELSE", "IF_END", "COPITH_IF_ALT_FIRE", "COPITH_IF_PLAYER",},
    {"GLIMMERS_EXPANDED_COLOUR_PINK", "COLOUR_RED", "COLOUR_ORANGE", "COLOUR_YELLOW", "COLOUR_GREEN", "COLOUR_BLUE", "COLOUR_PURPLE", "COLOUR_RAINBOW", "COLOUR_INVIS", "GRAHAM_GOLDEN", "GLIMMERS_EXPANDED_COLOUR_LAVA", "GLIMMERS_EXPANDED_COLOUR_ACID", "GLIMMERS_EXPANDED_COLOUR_LC", "GLIMMERS_EXPANDED_COLOUR_MIDAS",},
    {"FREEZE", "ELECTRIC_CHARGE", "GRAHAM_GRAB_BAG", "COPITH_ALCOHOL_SHOT", "COPITH_PAPER_SHOT", "APOTHEOSIS_FIRE_CHARGE", "APOTHEOSIS_GLUE_CHARGE",},
    {"SUN_POWER", "MOON_POWER",},
    {"EXPANDING_ORB", "GRAHAM_ORB_BLUE", "GRAHAM_ORB_BLUE_TIMER",},
    {"GRAHAM_MANAHEART", "GRAHAM_MANAHEARTBREAK",},
    {"GRAHAM_TOGGLER", "GRAHAM_TOGGLER2", "GRAHAM_TOGGLEROFF", "GRAHAM_TOGGLER_ALT", "GRAHAM_TOGGLER2_ALT", "GRAHAM_TOGGLER3_ALT",},
    {"GRAHAM_TOGGLE_RED", "GRAHAM_TOGGLE_BLUE", "GRAHAM_TOGGLE_GREEN", "GRAHAM_TOGGLE_YELLOW",},
    {"GRAHAM_MINI_HEATWAVE", "GRAHAM_MINI_FREEZEFIELD", "GRAHAM_MINI_DISSOLVEPOWDERS", "GRAHAM_MINI_ATTRACTGOLD", "GRAHAM_MINI_ELECTRICITY", "GRAHAM_MINI_NOKNOCKBACK", "GRAHAM_MINI_MIDASMEAT",},
    {"GRAHAM_BLACKLIGHT_ARROW", "GRAHAM_BLACKLIGHT_ARROW_TRIGGER", "GRAHAM_BLACKLIGHT_ARROW_TIMER",},
    {"GRAHAM_REDHANDS", "GRAHAM_HANDPORTAL",},
    {"GRAHAM_BRAMBALL", "GRAHAM_BRAMBALL_TRIGGER",},
    {"GRAHAM_VIBRANT_BULB", "GRAHAM_DIM_BULB",},
    {"GRAHAM_GLOW_DART", "GRAHAM_SHOCK_DART",},
    {"GRAHAM_SHIELD_DRONE", "GRAHAM_ATTACK_DRONE",}, -- no support drone
    {"CRITICAL_HIT", "GRAHAM_CRIT_DOWN",},
    {"FLY_UPWARDS", "FLY_DOWNWARDS", "GRAHAM_DIVEBOMB",},
    -- no souls here because that would defeat the point

    -- modded spell lists

    -- Copi's Things
    {"COPITH_ACID", "COPITH_CEMENT", "SPELLBOUND_SHRAPNEL_SHOT",}, -- acid/cement/shrapnel shot
    {"COPITH_ACTION_INVERSION", "COPITH_LOOP_CAST",}, -- meta spells. too strong? these should probably go in separate lists
    {"COPITH_DUPLICATE_ACTION", "COPITH_DUPLICATE_ACTION_2", "COPITH_DUPLICATE_ACTION_3",},
    {"COPITH_IMPRINT", "COPITH_SPINDOWN",},
    -- tbh, I bet we could do something funnily meta with these spells here. If a spell is placed in more than one list, it'll be used in the first list. So what we can do is place one spell in a lower list, and when it rotates to that spell, it will begin the rotation in a higher list that it's also in.
    {"COPITH_BOMB_SMALL", "BOMB", "COPITH_ALT_FIRE_BOMB", "APOTHEOSIS_BOMB_GIGA",}, -- bombs
    {"GLITTER_BOMB", "COPITH_STUN_BOMBS",},
    {"COPITH_COIN", "COPITH_ALT_FIRE_COIN",}, -- ultrakill!!!!!!!! headshot + railcoin + disrespect + l-ratio
    {"FLAMETHROWER", "COPITH_ALT_FIRE_FLAMETHROWER",}, -- flamethrowers, if there is an ice thrower I'll put that there too
    {"HOOK", "COPITH_GRAPPLING_HOOK", "COPITH_ALT_FIRE_GRAPPLING_HOOK",},
    {"COPITH_AMMO_BOX", "COPITH_AMMO_FROM_HP",}, -- too strong? idk, these spells are very uncommon
    {"COPITH_ARCANE_TURRET", "COPITH_ARCANE_TURRET_PATIENT",},
    {"APOTHEOSIS_AUTOFIRE", "COPITH_AUTO_ENEMIES", "COPITH_AUTO_FRAME", "COPITH_AUTO_HOLSTER", "COPITH_AUTO_HP", "COPITH_AUTO_HURT", "COPITH_AUTO_HP",},
    {"COPITH_BURST_FIRE",},
    {"COPITH_CAUSTIC_CLAW", "COPITH_VACUUM_CLAW",},
    {"INFESTATION", "COPITH_CHAOS_SPRITES", "GOKI_CHAOTIC_BURST",},
    {"SOILBALL", "COPITH_CHUNK_OF_RANDOM", "COPITH_CONCRETEBALL", "GRAHAM_WOOD", "CC_METAL_SEASONING", "CC_URANIUMBALL",}, -- Chunk of X
    {"LIGHT", "COPITH_CLAIRVOYANCE",}, -- Spells that reveal areas.
    {"COPITH_CONFETTI_TRAIL", "COPITH_LOVELY_TRAIL", "COPITH_RAINBOW_TRAIL", "COPITH_SPARKLING_TRAIL", "COPITH_STARRY_TRAIL", "COPITH_SUS_TRAIL", "COPITH_NULL_TRAIL",},
    {"COPITH_DECOY", "COPITH_DECOY_TRIGGER",},
    {"COPITH_DELAY_2", "COPITH_DELAY_3", "COPITH_DELAY_X",},
    {"COPITH_GATE_HP", "COPITH_GATE_MANA",},
    {"COPITH_GUNNER_SHOT", "COPITH_GUNNER_SHOT_STRONG",},
    {"COPITH_HITFX_OILED_2X_DAMAGE_BURN", "COPITH_HITFX_BLOODY_2X_DAMAGE_POISONED", "COPITH_HITFX_WET_2X_DAMAGE_FREEZE",}, -- should these go with the other hitfx spells? I don't think so, given that the explosion hitfx spells have their own category. but charm on toxic is with the crits...
    {"COPITH_LIQUID_EATER", "MATTER_EATER", "SPELLBOUND_BLACKHOLE_INFUSION",}, -- how strong?
    {"ENERGY_SHIELD_SHOT", "COPITH_MINI_SHIELD",},
    {"PROPANE_TANK", "COPITH_POLY_PROPANE_TANK",},
    {"COPITH_REDIRECT_THIS", "COPITH_REDIRECT_THIS_RARE",},
    {"COPITH_RIPHOOK", "COPITH_ALT_FIRE_RIPHOOK",},
    {"TINY_GHOST", "COPITH_SHIELD_GHOST",},
    {"COPITH_SILVER_BULLET", "COPITH_SILVER_BULLET_DEATH_TRIGGER", "COPITH_SILVER_BULLET_ON_DEATH", "COPITH_SILVER_MAGNUM", "COPITH_SILVER_MAGNUM_DEATH_TRIGGER",},
    {"COPITH_GILDED_AXE", "COPITH_STARLIGHT_AXE",}, -- thoughts? I kinda like it
    {"COPITH_SUMMON_FLASK", "COPITH_SUMMON_FLASK_FULL", "POTION_RAIN"--[[More Stuff]], "GRAHAM_COFFEE", "COPITH_SUMMON_JAR_URINE",},
    {"SUMMON_ROCK", "COPITH_SUMMON_ANVIL", "METEORITE"--[[More Stuff]],},
    {"COPITH_TELEPORT", "COPITH_TELEPORT_BAD",},
    {"COPITH_ULT_CONTROL", "SPELLBOUND_CONTROL", "COPITH_ULT_DAMAGE", "COPITH_ULT_DRAW_MANY", "COPITH_ULT_LIFETIME", "COPITH_ULT_PROTECTION", "GOKI_PROTECTIVE_ENCHANTMENT", "COPITH_ULT_RECHARGE",}, -- It feels out of place to include spellbound stuff in copi's ults, but their functions are too similar... I need feedback on this.
    {"COPITH_GLITTERING_TRAIL", "GOKI_GLITTERING_TRAIL", "COPITH_BARRIER_TRAIL", "GOKI_BARRIER_TRAIL", "COPITH_DEATH_CROSS_TRAIL", "SPELLBOUND_TRAIL_OF_ROCK_SPIRITS",},

    -- Apotheosis
    {"REGENERATION_FIELD", "APOTHEOSIS_ALT_FIRE_COV",}, -- how strong?
    {"APOTHEOSIS_TARGETTER", "APOTHEOSIS_ALT_FIRE_TARGETTER",},
    {"APOTHEOSIS_BLOOD_POWER", "APOTHEOSIS_FIRE_POWER", "APOTHEOSIS_WATER_POWER",},
    {"APOTHEOSIS_BUNGAL_SHIFT", "APOTHEOSIS_BUNGAL_SHIFT_SPAM", "CC_LOCAL_SHIFT",}, -- does this defeat the purpose of experimenting with mass materia conversion? (if it's not unlocked yet, then it won't spawn)
    {"APOTHEOSIS_HEX_BLOOD", "APOTHEOSIS_HEX_OIL", "APOTHEOSIS_HEX_BLOOD",},
    {"APOTHEOSIS_LIQUIDSPHERE_ACID", "APOTHEOSIS_LIQUIDSPHERE_TELEPORTATIUM", "APOTHEOSIS_LIQUIDSPHERE_WATER",},
    {"WORM_RAIN", "APOTHEOSIS_MASS_BURROW",},
    {"APOTHEOSIS_MASS_STATUS_DRUNK", "APOTHEOSIS_MASS_STATUS_FIRE", "APOTHEOSIS_MASS_STATUS_POLYMORPH", "APOTHEOSIS_MASS_STATUS_POLYMORPH_INTENSE", "APOTHEOSIS_MASS_STATUS_URINE", "APOTHEOSIS_MASS_STATUS_WET", "APOTHEOSIS_MASS_DRY",},
    {"APOTHEOSIS_MUSICAL_STRIKE", "APOTHEOSIS_MUSICAL_STRIKE_TRIGGER",},
    {"POLLEN", "APOTHEOSIS_POLLEN_TRIGGER",},
    {"APOTHEOSIS_PORTAL_LUKKI_BLUE_PORTAL", "APOTHEOSIS_PORTAL_LUKKI_GREEN_PORTAL", "APOTHEOSIS_PORTAL_LUKKI_RED_PORTAL",}, -- Maybe this is too powerful?
    {"APOTHEOSIS_RAT_BITE", "APOTHEOSIS_RAT_BITE_CRIT", "KUPOLI_MAGICAL_RAT_KING",},
    {"RUBBER_BALL", "APOTHEOSIS_RUBBER_BALL_TRIGGER",},
    {"APOTHEOSIS_STAR_SHOT", "SHOOTING_STARS"--[[More Stuff]],},
    

    -- Tales of Kupoli
    {"KUPOLI_ALL_REAP_FLY", "KUPOLI_ALL_REAP_GILDED", "KUPOLI_ALL_REAP_MAGE", "KUPOLI_ALL_REAP_SPIDER",},
    {"KUPOLI_RANDOM_REAP", "KUPOLI_REAPING_SHOT", "KUPOLI_SOULDOS",}, -- should these go together?
    {"KUPOLI_HIISI_GLUE_SHOT", "KUPOLI_HIISI_PISTOL", "KUPOLI_HIISI_POISON_SHOT", "KUPOLI_HIISI_SHOTGUN", "KUPOLI_HIISI_SNIPER","KUPOLI_SNIPER_BEAM", "KUPOLI_ROBOT_FLAME", "KUPOLI_ROBOT_ICER",},
    {"KUPOLI_SOUL_NECROMANCY", "KUPOLI_SOUL_MINIONS_TO_HEALING", "KUPOLI_SOUL_MINIONS_TO_NUKES",},
    {"METEOR", "KUPOLI_SOUL_METEOR",},
    {"KUPOLI_WEAKENING_HALO", "KUPOLI_REAPING_HALO",},
    {"GRAHAM_SACRIFICE", "KUPOLI_CRYSTALLISE_SOULS",},

    -- Graham's Things
    {"ARROW", "GRAHAM_QUIVER",},
    {"GRAHAM_WILLOWISP", "CC_WISPY_FLAME",},

    -- More Stuff
    {"LASER_EMITTER_WIDER", "LASER_EMITTER_FOCUS"--[[More Stuff]],},

    -- Chemical Curiosities
    {"CC_FIRE_TO_GREASE", "CC_GUNPOWDER_BUFF",},

    -- Spellbound
    {"SPELLBOUND_BLOOM_SHOT", "ACIDSHOT",},
    {"COPITH_ZAP", "GOKI_ZAP", "LIGHTNING", "SPELLBOUND_CHAIN_LIGHTNING",},
    {"SPELLBOUND_FORCE_MODULE", "COPITH_STORED_SHOT",},
    {"SPELLBOUND_PYRE_ENCHANTMENT", "SPELLBOUND_LIGHTNING_INFUSION",},
    {"SPELLBOUND_AIR_BURST", "SPELLBOUND_FROZEN_CORE", "SPELLBOUND_HEAT_WAVE", "SPELLBOUND_VOID_SHOT",},
    {"SPELLBOUND_SLIME_AURA", "SPELLBOUND_TOXIC_AURA", "SPELLBOUND_WHISKEY_AURA",},
    {"SPELLBOUND_GAS_SHOT", "SPELLBOUND_GAS_SHOT_CONCRETE", "SPELLBOUND_GAS_SHOT_FIRE", "SPELLBOUND_GAS_SHOT_FREEZING", "SPELLBOUND_GAS_SHOT_POISON",},
    {"SPELLBOUND_GHOSTLY_LANCE", "SPELLBOUND_DUCK",},
    {"BUCKSHOT", "SPELLBOUND_SHARD_SHOT", "SPELLBOUND_DARK_FLAME_TRAIL",},
    {"SPELLBOUND_STICKY_BOMB", "SPELLBOUND_STICKY_BOMB_TRIGGER",},
    {"COPITH_ICICLE_LANCE", "SPELLBOUND_ICE_SHARD",},
    {"SPELLBOUND_VACUUM_SHOT", "SPELLBOUND_BULLET_VORTEX",},
}
